SELECT A.NOMBRE,
       A.CORREO,
       C.NOMBRE_LUGAR,
       D.GENERO
FROM TBL_USUARIOS A
LEFT JOIN TBL_LUGARES C
ON (A.CODIGO_LUGAR = C.CODIGO_LUGAR)
LEFT JOIN TBL_GENEROS D
ON (A.CODIGO_GENERO = D.CODIGO_GENERO);

SELECT A.NOMBRE,
       C.COSTO,
       D.NOMBRE_PROPIETARIO,
       E.NOMBRE_MONEDA,
       F.NOMBRE_ENTIDAD
FROM TBL_USUARIOS A
INNER JOIN TBL_FACTURAS C
ON (A.CODIGO_USUARIO = C.CODIGO_USUARIO)
INNER JOIN TBL_MEDIOS_BANCARIOS D
ON (C.CODIGO_MEDIO_PAGO = D.CODIGO_MEDIO)
INNER JOIN TBL_MONEDAS E
ON (D.CODIGO_MONEDA = E.CODIGO_MONEDA)
INNER JOIN TBL_ENTIDADES_FINANCIERAS F
ON (D.CODIGO_ENTIDAD = F.CODIGO_ENTIDAD);

SELECT A.NOMBRE,
       C.ESPACIO_ALMACENAMIENTO,
       C.PRECIO,
       D.COSTO
FROM TBL_USUARIOS A
INNER JOIN TBL_TIPOS_CUENTAS C
ON (A.CODIGO_TIPO = C.CODIGO_TIPO)
INNER JOIN TBL_FACTURAS D
ON (C.CODIGO_TIPO = D.CODIGO_TIPO_CUENTA)
;

SELECT A.COSTO,
       C.NOMBRE,
       D.NOMBRE_UNIDAD
FROM TBL_FACTURAS A
INNER JOIN TBL_TIPOS_CUENTAS C
ON (A.CODIGO_TIPO_CUENTA = C.CODIGO_TIPO)
INNER JOIN TBL_UNIDADES D
ON (C.CODIGO_UNIDAD = D.CODIGO_UNIDAD)
;














