CREATE VIEW VW_CP_SEG AS 
SELECT A.NOMBRE AS NOMBRE_USUARIO,
        B.ARCHIVO_COPIA,
        B.FECHA_HORA_COPIA
FROM TBL_USUARIOS A,
        TBL_COPIAS_DE_SEGURIDAD B
WHERE B.CODIGO_USUARIO = A.CODIGO_USUARIO;

SELECT *
FROM VW_CP_SEG;

CREATE VIEW VW_ORD_REG AS 
SELECT A.NOMBRE_MARCA AS MARCA,
        B.NOMBRE_SISTEMA AS SISTEMA_OPERATIVO,
        C.NOMBRE_VERSION AS VERSION_SO,
        D.MODELO AS PROCESADOR,
        E.NOMBRE AS USUARIO,
        F.FECHA_REGISTRO
FROM TBL_MARCAS A,
        TBL_SISTEMAS_OPERATIVOS B,
        TBL_VERSIONES C,
        TBL_PROCESADORES D,
        TBL_USUARIOS E,
        TBL_ORDENADORES F
WHERE F.CODIGO_MARCA = A.CODIGO_MARCA AND
        B.CODIGO_SISTEMA = F.CODIGO_SISTEMA AND
        C.CODIGO_VERSION =B.CODIGO_VERSION AND
        F.CODIGO_PROCESADOR = D.CODIGO_PROCESADOR AND
        F.CODIGO_USUARIO = E.CODIGO_USUARIO;
        
SELECT *
FROM VW_ORD_REG;

CREATE VIEW VW_ARC_REG AS 
SELECT A.NOMBRE AS ARCHIVO,
        B.NOMBRE AS CARPETA,
        C.NOMBRE AS USUARIO
FROM TBL_ARCHIVOS A
LEFT JOIN TBL_CARPETAS B
ON(A.CODIGO_CARPETA = B.CODIGO_CARPETA)
LEFT JOIN TBL_USUARIOS C
ON(A.CODIGO_USUARIO = C.CODIGO_USUARIO);

SELECT *
FROM VW_ARC_REG;