ALTER TABLE DRIVE.TBL_SERVICIOS_ELECTRONICOS DISABLE CONSTRAINT SER_ELE_USU_FK;

insert into TBL_SERVICIOS_ELECTRONICOS (CODIGO_SERVICIO, CODIGO_USUARIO, NOMBRE_SERVICIO, TELEFONO, NOMBRE_USUARIO, CONTRASENIA) values (1, 21, 'PAYPAL', '461-312-1574', 'gmolina', 'passw0rd');
insert into TBL_SERVICIOS_ELECTRONICOS (CODIGO_SERVICIO, CODIGO_USUARIO, NOMBRE_SERVICIO, TELEFONO, NOMBRE_USUARIO, CONTRASENIA) values (2, 34, 'GOOGLE WALLET', '993-731-8958', 'avillamar', 'class05');

ALTER TABLE DRIVE.TBL_SERVICIOS_ELECTRONICOS ENABLE CONSTRAINT SER_ELE_USU_FK;