insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (1, 6, 'COREi7', 3.9);
insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (2, 7, 'RYZEN', 4.2);
insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (3, 7, 'ATHLON', 2.5);
insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (4, 7, 'FX', 1.2);
insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (5, 6, 'COREi3', 3.8);
insert into TBL_PROCESADORES (CODIGO_PROCESADOR, CODIGO_MARCA, MODELO, FRECUENCIA) values (6, 7, 'ASERIES', 2.0);
