insert into TBL_SERVICIOS_ELECTRONICOS (CODIGO_SERVICIO, NOMBRE_SERVICIO, TELEFONO) values (1, 'PAYPAL', '461-312-1574');
insert into TBL_SERVICIOS_ELECTRONICOS (CODIGO_SERVICIO, NOMBRE_SERVICIO, TELEFONO) values (2, 'GOOGLE WALLET', '993-731-8958');
