ALTER TABLE DRIVE.TBL_BENEFICIOS_X_CUENTA DISABLE CONSTRAINT BEN_X_CUE_TIP_CUE_FK;
ALTER TABLE DRIVE.TBL_BENEFICIOS_X_CUENTA DISABLE CONSTRAINT BEN_X_CUE_BEN_FK;

insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (2, 1);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (3, 1);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (3, 2);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (4, 1);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (4, 2);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (4, 3);

ALTER TABLE DRIVE.TBL_BENEFICIOS_X_CUENTA ENABLE CONSTRAINT BEN_X_CUE_TIP_CUE_FK;
ALTER TABLE DRIVE.TBL_BENEFICIOS_X_CUENTA ENABLE CONSTRAINT BEN_X_CUE_BEN_FK;