insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (1, 'Fotolia', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (2, 'SoundBust', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (3, 'TexEditor', '#', 'generic-app.png' );
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (4, 'FilterWay', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (5, 'BeanFilters', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (6, 'PrintXr', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (7, 'Docs2Go', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (8, 'Apptoid', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (9, 'Music4u', '#', 'generic-app.png');
insert into TBL_APLICACIONES_TERCEROS (codigo_aplicacion, nombre_aplicacion, enlace_aplicacion, icono_aplicacion) values (10, 'AtenaCam', '#', 'generic-app.png');