ALTER TABLE DRIVE.TBL_FACTURAS DISABLE CONSTRAINT FAC_USU_FK;
ALTER TABLE DRIVE.TBL_FACTURAS DISABLE CONSTRAINT FAC_MED_BAN_FK;
ALTER TABLE DRIVE.TBL_FACTURAS DISABLE CONSTRAINT FAC_TIP_CUE_FK;

insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (1, 31, 1, 4, TO_DATE('1/26/2019','mm/dd/yyyy'), 2.66, 1.31, 42);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (2, 21, 2, 3, TO_DATE('2/25/2019','mm/dd/yyyy'), 2.25, 1.01, 28);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (3, 41, 6, 2, TO_DATE('4/29/2018','mm/dd/yyyy'), 2.55, 1.7, 12);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (4, 41, 6, 2, TO_DATE('10/26/2018','mm/dd/yyyy'), 2.75, 2.04, 22);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (5, 24, 4, 3, TO_DATE('5/4/2018','mm/dd/yyyy'), 2.9, 1.22, 32);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (6, 27, 8, 3, TO_DATE('12/22/2018','mm/dd/yyyy'), 2.12, 1.77, 29);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (7, 31, 3, 4, TO_DATE('1/11/2019','mm/dd/yyyy'), 1.93, 2.07, 31);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (8, 48, 6, 3, TO_DATE('8/14/2018','mm/dd/yyyy'), 2.26, 1.17, 40);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (9, 19, 10, 2, TO_DATE('7/30/2018','mm/dd/yyyy'), 2.86, 1.18, 13);
insert into TBL_FACTURAS  (CODIGO_FACTURA, CODIGO_USUARIO, CODIGO_MEDIO_PAGO, CODIGO_TIPO_CUENTA, FECHA_FACTURACION, COSTO, IMPUESTO, DESCUENTO) values (10, 18, 9, 4, TO_DATE('4/7/2019','mm/dd/yyyy'), 2.21, 2.07, 48);

ALTER TABLE DRIVE.TBL_FACTURAS ENABLE CONSTRAINT FAC_USU_FK;
ALTER TABLE DRIVE.TBL_FACTURAS ENABLE CONSTRAINT FAC_MED_BAN_FK;
ALTER TABLE DRIVE.TBL_FACTURAS ENABLE CONSTRAINT FAC_TIP_CUE_FK;