insert into TBL_VERSIONES (CODIGO_VERSION, CODIGO_SISTEMA, NOMBRE_VERSION) values (1, 2, 'UBUNTU');
insert into TBL_VERSIONES (CODIGO_VERSION, CODIGO_SISTEMA, NOMBRE_VERSION) values (2, 2, 'DEBIAN');
insert into TBL_VERSIONES (CODIGO_VERSION, CODIGO_SISTEMA, NOMBRE_VERSION) values (3, 1, 'WINDOWS XP');
insert into TBL_VERSIONES (CODIGO_VERSION, CODIGO_SISTEMA, NOMBRE_VERSION) values (4, 1, 'WINDOWS 10');
