insert into TBL_VERSIONES (CODIGO_VERSION, NOMBRE_VERSION) values (1, 'UBUNTU');
insert into TBL_VERSIONES (CODIGO_VERSION, NOMBRE_VERSION) values (2, 'DEBIAN');
insert into TBL_VERSIONES (CODIGO_VERSION, NOMBRE_VERSION) values (3, 'WINDOWS XP');
insert into TBL_VERSIONES (CODIGO_VERSION, NOMBRE_VERSION) values (4, 'WINDOWS 10');
