insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, ESPACIO_ALMACENAMIENTO, PRECIO) values (1, 1, 1, 2.66);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, ESPACIO_ALMACENAMIENTO, PRECIO) values (2, 2, 1, 1.89);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, ESPACIO_ALMACENAMIENTO, PRECIO) values (3, 3, 1, 2.92);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, ESPACIO_ALMACENAMIENTO, PRECIO) values (4, 2, 1, 2.2);
