ALTER TABLE DRIVE.TBL_TIPOS_CUENTAS DISABLE CONSTRAINT TIP_CUE_UNI_FK;

insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, NOMBRE, ESPACIO_ALMACENAMIENTO, PRECIO) values (1, 4, 'Free', 15, 0);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, NOMBRE, ESPACIO_ALMACENAMIENTO, PRECIO) values (2, 4, 'Premium Basico', 100, 29);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, NOMBRE, ESPACIO_ALMACENAMIENTO, PRECIO) values (3, 4, 'Premium Intermedio', 250, 49);
insert into TBL_TIPOS_CUENTAS (CODIGO_TIPO, CODIGO_UNIDAD, NOMBRE, ESPACIO_ALMACENAMIENTO, PRECIO) values (4, 4, 'Premium Avanzado', 500, 99);

ALTER TABLE DRIVE.TBL_TIPOS_CUENTAS ENABLE CONSTRAINT TIP_CUE_UNI_FK;