insert into TBL_MONEDAS (CODIGO_MONEDA, NOMBRE_MONEDA, ABREVIATURA) values (1, 'LEMPIRAS', 'LPS');
insert into TBL_MONEDAS (CODIGO_MONEDA, NOMBRE_MONEDA, ABREVIATURA) values (2, 'DOLAR', '$');
insert into TBL_MONEDAS (CODIGO_MONEDA, NOMBRE_MONEDA, ABREVIATURA) values (3, 'EURO', '€');
