insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (1, null, 'Mexico', 15.85, 0.02);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (2, null, 'Russia', 39.79, 38.07);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (3, null, 'Afghanistan', 61.23, 62.75);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (4, null, 'United States', 43.43, 35.77);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (5, null, 'Philippines', 0.73, 54.28);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (6, null, 'Zambia', 57.57, 6.79);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (7, null, 'Tunisia', 82.24, 25.62);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (8, null, 'Syria', 109.3, 73.02);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (9, null, 'France', 69.23, 41.08);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (10, null, 'Russia', 30.5, 76.67);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (11, null, 'Czech Republic', 115.13, 26.93);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (12, null, 'Philippines', 6.8, 26.71);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (13, null, 'Peru', 54.15, 89.14);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (14, null, 'Indonesia', 24.58, 40.9);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (15, null, 'Venezuela', 171.34, 55.61);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (16, null, 'United States', 120.19, 22.78);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (17, null, 'Mexico', 73.45, 57.85);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (18, null, 'China', 114.9, 74.12);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (19, null, 'Indonesia', 3.6, 18.84);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (20, null, 'Russia', 126.88, 24.45);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (21, null, 'Canada', 53.03, 84.45);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (22, null, 'Brazil', 120.56, 86.36);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (23, null, 'Czech Republic', 15.36, 43.9);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (24, null, 'Czech Republic', 69.28, 66.08);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (25, null, 'Thailand', 127.23, 19.33);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (26, null, 'Slovenia', 158.85, 68.7);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (27, null, 'New Zealand', 110.35, 37.1);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (28, null, 'Ukraine', 4.33, 83.57);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (29, null, 'France', 154.91, 62.2);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (30, null, 'France', 162.37, 40.35);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (31, null, 'Latvia', 114.11, 34.51);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (32, null, 'Bosnia and Herzegovina', 63.95, 25.95);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (33, null, 'China', 156.11, 52.08);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (34, null, 'Bangladesh', 152.15, 57.79);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (35, null, 'Thailand', 108.89, 63.7);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (36, null, 'China', 110.43, 24.62);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (37, null, 'Brazil', 39.74, 66.91);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (38, null, 'Vietnam', 149.99, 63.57);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (39, null, 'Argentina', 35.59, 78.72);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (40, null, 'Thailand', 144.27, 79.32);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (41, null, 'Portugal', 107.75, 51.43);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (42, null, 'Indonesia', 111.41, 46.31);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (43, null, 'Vietnam', 110.81, 64.23);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (44, null, 'Afghanistan', 10.86, 72.73);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (45, null, 'Sweden', 162.34, 3.2);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (46, null, 'Philippines', 130.92, 87.75);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (47, null, 'Greece', 177.96, 33.53);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (48, null, 'China', 114.93, 82.91);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (49, null, 'Greece', 78.34, 16.04);
insert into TBL_LUGARES (codigo_lugar, codigo_lugar_padre, nombre_lugar, longitud, latitud) values (50, null, 'Poland', 116.22, 5.73);
