insert into TBL_BENEFICIOS (CODIGO_BENEFICIO, NOMBRE_BENEFICIO) values (1, 'AYUDA DE EXPERTOS DE GOOGLE');
insert into TBL_BENEFICIOS (CODIGO_BENEFICIO, NOMBRE_BENEFICIO) values (2, 'OPCIÓN DE AÑADIR FAMILIA');
insert into TBL_BENEFICIOS (CODIGO_BENEFICIO, NOMBRE_BENEFICIO) values (3, 'VENTAJA PARA SUSCRIPTORES');
