insert into TBL_UNIDADES (CODIGO_UNIDAD, NOMBRE_UNIDAD, ABREVIATURA) values (1, 'Byte', 'Byte');
insert into TBL_UNIDADES (CODIGO_UNIDAD, NOMBRE_UNIDAD, ABREVIATURA) values (2, 'Kilobyte', 'KB');
insert into TBL_UNIDADES (CODIGO_UNIDAD, NOMBRE_UNIDAD, ABREVIATURA) values (3, 'Megabyte', 'MB');
insert into TBL_UNIDADES (CODIGO_UNIDAD, NOMBRE_UNIDAD, ABREVIATURA) values (4, 'Gigabyte', 'GB');
