ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS DISABLE CONSTRAINT MED_BAN_ENT_FIN_FK;
ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS DISABLE CONSTRAINT MED_BAN_MON_FK;
ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS DISABLE CONSTRAINT MED_BAN_USU_FK;

insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (1, 1, 2, 39, '442-593-4122', 'Symon Riediger', TO_DATE('04/2019','mm/yyyy'), 6309);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (2, 1, 2, 21, '813-460-5924', 'Bastien Mellish', TO_DATE('05/2018','mm/yyyy'), 4597);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (3, 2, 1, 19, '458-256-3333', 'Gabriel Berger', TO_DATE('07/2018','mm/yyyy'), 8008);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (4, 2, 2, 30, '659-831-2525', 'Eudora Hatchman', TO_DATE('05/2018','mm/yyyy'), 6428);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (5, 3, 1, 28, '869-840-7816', 'Miller Pauley', TO_DATE('05/2018','mm/yyyy'), 5272);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (6, 1, 2, 32, '963-484-8066', 'Kile Morfell', TO_DATE('08/2018','mm/yyyy'), 6237);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (7, 1, 2, 38, '432-964-0216', 'Wileen Cabbell', TO_DATE('03/2019','mm/yyyy'), 7016);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (8, 3, 1, 47, '966-126-7251', 'Dominique Anfonsi', TO_DATE('06/2018','mm/yyyy'), 5431);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (9, 3, 3, 46, '924-326-7233', 'Fredelia Ondrusek', TO_DATE('10/2018','mm/yyyy'), 8157);
insert into TBL_MEDIOS_BANCARIOS (CODIGO_MEDIO, CODIGO_ENTIDAD, CODIGO_MONEDA, CODIGO_USUARIO, NUMERO_TARJETA, NOMBRE_PROPIETARIO, FECHA_CADUCIDAD, CODIGO_TARJETA) values (10, 2, 3, 49, '848-158-3114', 'Marty Merriday', TO_DATE('01/2019','mm/yyyy'), 6333);

ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS ENABLE CONSTRAINT MED_BAN_ENT_FIN_FK;
ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS ENABLE CONSTRAINT MED_BAN_MON_FK;
ALTER TABLE DRIVE.TBL_MEDIOS_BANCARIOS ENABLE CONSTRAINT MED_BAN_USU_FK;