insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (1, 3);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (2, 1);
insert into TBL_BENEFICIOS_X_CUENTA (CODIGO_TIPO_CUENTA, CODIGO_BENEFICIO) values (3, 2);
