insert into TBL_ENTIDADES_FINANCIERAS (CODIGO_ENTIDAD, NOMBRE_ENTIDAD, TELEFONO) values (1, 'LAFISE', '323-723-9646');
insert into TBL_ENTIDADES_FINANCIERAS (CODIGO_ENTIDAD, NOMBRE_ENTIDAD, TELEFONO) values (2, 'FICOHSA', '425-514-4414');
insert into TBL_ENTIDADES_FINANCIERAS (CODIGO_ENTIDAD, NOMBRE_ENTIDAD, TELEFONO) values (3, 'DAVIVIENDA', '665-220-3560');
