insert into TBL_UNIDADES (CODIGO_UNIDADES, NOMBRE_UNIDAD, ABREVIATURA) values (1, 'Megen', 'Piggy');
insert into TBL_UNIDADES (CODIGO_UNIDADES, NOMBRE_UNIDAD, ABREVIATURA) values (2, 'Berkie', 'Dawna');
insert into TBL_UNIDADES (CODIGO_UNIDADES, NOMBRE_UNIDAD, ABREVIATURA) values (3, 'Odetta', 'Isa');
insert into TBL_UNIDADES (CODIGO_UNIDADES, NOMBRE_UNIDAD, ABREVIATURA) values (4, 'Olivier', 'Drud');
